markdown: kramdown
kramdown:
  input: GFM
baseurl: /PugnaPorcorum
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
name: Git Classics - Pugna Porcorum
url: https://gitclassics.github.io/PugnaPorcorum
